name: Release Assets

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-linux-macos:
    name: Build for Linux and macOS
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Configure Nix cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Build the project
        run: |
          nix develop --command make

      - name: Create release asset
        run: |
          cd build
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then \
            OS_NAME="linux"; \
          else \
            OS_NAME="macos"; \
          fi
          tar -czf todocxx-${OS_NAME}.tar.gz todocxx

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/todocxx-*.tar.gz
